### ISSUE TITLE
Some gotchas to getting this project to build

### ISSUE THREAD

**Issue by ykcreations** [samsungsamiio/sami-ios-demo#1]
I had trouble building the project in the first place. Not sure if this is a problem on my local setup, but if it's not I thought it'd be nice to save people some trouble. Adding to the instructions in the README:

- After downloading example app, delete the Pods folder and SAMIClient.xcworkspace
- Make sure your Podfile 'platform :ios' and your project's deployment target versions match
- Make sure your Podfile links both `SAMIClient` and `SAMIClientTests` by appending to it:

 ```link_with 'SAMIClient', 'SAMIClientTests'```
- Run `pod install`
- Open `SAMIClient.xcworkspace` (not `SAMIClient.xcodeproj`)
- Drag the SDK folder as indicated in README
- Make sure that everything is linked correctly (see  the answer by `waggles` on [this Stackoverlow question](http://stackoverflow.com/questions/12002905/ios-build-fails-with-cocoapods-cannot-find-header-files))
- Finally, compile.

Hope this helps.

**Comment by yujingwu** [comment]
I will look into it. If it is a general problem, I will take your advice to update README.

**Comment by ykcreations** [comment]
Great - thanks, Yujing :+1:

**Comment by ykcreations** [comment]
Great -- I see you've made most of the changes.
Quick note, it's important to delete the Pods folder and then run `pod install` -- you can't just download installed pods and have them work for some reason, you have to have CocoaPods download them for you.

**Comment by ykcreations** [comment]
Also, the current Podfile still lists iOS 7.0. Don't know if that affects deployment, but since you built this for iOS 8 anyway, shouldn't it match?

**Comment by yujingwu** [comment]
The SAMI SDK requires iOS 7.0 or above. The demo app requires iOS 8.0 since the app uses Pedometer classes of iOS 8.  The SDK doesn’t have the same dependency as the app. 
So you can use iOS 7 to build and run the app using the SAMI iOS SDK.

**Comment by ykcreations** [comment]
Fair play. Thanks for the explanation.

**Comment by yujingwu** [comment]
Regarding your comments "Quick note, it's important to delete the Pods folder and then run pod install"

There is no Pods folder any more in the new source tree. I have deleted it. It will be generated when running "pod install". So I do not need to add that into the README.
