### ISSUE TITLE
Sample app doesn't sync with SAMI

### ISSUE THREAD

**Issue by ykcreations** [samsungsamiio/sami-ios-demo#2]
I noticed that the synchPedometer implementation is all commented out in [SamiSynchPedometerViewController.m](https://github.com/samsungsamiio/sami-ios-demo/blob/167bb2b1bbc9291ba32f1ac3b67ca663613e0fdf/SAMIClient/SAMIClient/SamiSynchPedometerViewController.m). Is this still being implemented?

**Comment by yujingwu** [comment]
Will get back on this soon.

**Comment by yujingwu** [comment]
Actually not all implementation in that file is commented out. showPedometer method is being used.
The demo source files need cleanup. I have created https://github.com/samsungsamiio/sami-ios-demo/issues/3 to work on cleanup. Feel free to make comments there.
